services:
  - type: web
    name: discord-bot
    runtime: node
    plan: free
    buildCommand: npm install && pip3 install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_DB
        value: "false"
      - key: LEADERBOARD_ENABLED
        value: "true"
      - key: ACTIVE
        value: "true"
      - key: TELEMETRY_STATE
        value: "false"
    healthCheckPath: /api/health
    autoDeploy: true
